services:
  mysqlDb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: foyer
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-foyer:
    depends_on:
      - mysqlDb
    image: aymenzouaoui/zouaouiaymen5sim2:0.0.1  # Ensure the image name is all lowercase
    restart: on-failure
    ports:
      - "8085:8085"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqlDb:3306/foyer?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "rootpassword",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db:
