version: '2'


services:
  spring_app:
    image: youssefjemmali/mon_projet:v1.0
    container_name: spring_app
    depends_on:
      - mysql_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""  # Pas de mot de passe
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8081
      SERVER_SERVLET_CONTEXT_PATH: /Foyer
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
    ports:
      - "8082:8082"  # Remappez le port 8081 de l'application Spring vers le port 8081 de votre machine

  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ""  # Pas de mot de passe pour MySQL
      MYSQL_DATABASE: foyer
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
