### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/foyerdb
spring.datasource.username=root
spring.datasource.password=root
### JPA / HIBERNATE ###
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
server.port=8089
server.servlet.context-path=/Foyer